name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

env:
  IS_TAG: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')}}
  MASTER_PYTHON: "3.8"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.MASTER_PYTHON }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.MASTER_PYTHON }}
      - name: Install Poetry Itself
        run: pip install poetry
      - name: Poetry Install
        run: poetry install
      - name: Flake8
        run: poetry run flake8
      - name: Mypy
        run: poetry run mypy .
      - name: Black
        run: poetry run black --check .
      - name: Isort
        run: poetry run isort --check-only .
      - name: Shellcheck
        run: shellcheck scripts/*.sh

  test:
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8"]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Poetry Itself
        run: pip install poetry
      - name: Poetry Install
        run: poetry install
      - name: Pytest
        run: poetry run pytest
      - name: ASV
        run: |
          poetry run asv machine --machine travis --os unknown --arch unknown --cpu unknown --ram unknown
          poetry run asv run --show-stderr --environment existing --quick
      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          # NOTE: `token` is not required, because the rle-array repo is public
          file: ./coverage.xml
          name: pytest-${{ runner.OS }}-${{ matrix.python }}

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.MASTER_PYTHON }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.MASTER_PYTHON }}
      - name: Install Poetry Itself
        run: pip install poetry
      - name: Poetry Install
        run: poetry install
      - name: Sphinx
        run: |
          poetry run python setup.py build_sphinx
          touch ./docs/_build/html/.nojekyll
      - name: Preserve Docs
        uses: actions/upload-artifact@v2.2.2
        with:
          name: docs
          path: docs/_build/html
      - name: Deploy Docs
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html

  release:
    runs-on: ubuntu-latest
    needs: [lint, test, docs]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.MASTER_PYTHON }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.MASTER_PYTHON }}
      - name: Install Poetry Itself
        run: pip install poetry
      - name: Poetry Install
        run: poetry install
      - name: Build
        run: poetry build
      - name: Prepare Release Notes
        run: awk 'BEGIN{found=0} {if (match($0, "==============")) {if (found == 1) exit; found=1}; if (found == 1) {print last}; last=$0}' CHANGES.rst > release_notes.rst
      - name: Create Release Notes
        uses: docker://pandoc/core:2.9
        with:
          args: --from=rst --to=markdown -o release_notes.md release_notes.rst
      - name: Preserve Dist
        uses: actions/upload-artifact@v2.2.2
        with:
          name: dist
          path: dist
      - name: Preserve Release Notes
        uses: actions/upload-artifact@v2.2.2
        with:
          name: release_notes.md
          path: release_notes.md
      - name: Publish to PyPI
        if: env.IS_TAG == 'true'
        run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      - name: Create GitHub Release
        if: env.IS_TAG == 'true'
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: rle-array ${{ github.ref }}
          body_path: release_notes.md
          draft: false
          prerelease: false
